apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: istio-system
spec:
  interval: 1h0m0s
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: istio-system
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 14.11.0
  interval: 1h0m0s
  releaseName: prometheus
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    kubeStateMetrics:
      enabled: false
    alertmanager:
      enabled: false
    nodeExporter:
      enabled: false
    pushgateway:
      enabled: false
    server:
      fullnameOverride: prometheus
      persistentVolume:
        enabled: false
      podAnnotations:
        sidecar.istio.io/inject: "false"
      service:
        servicePort: 9090
    extraScrapeConfigs: |
      - job_name: "istiod"
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - istio-system
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: istiod;http-monitoring
        scrape_interval: 1m
        scrape_timeout: 10s
      - job_name: "envoy-stats"
        metrics_path: /stats/prometheus
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: ".*-envoy-prom"
        scrape_interval: 1m
        scrape_timeout: 10s
