apiVersion: flagger.app/v1beta1
kind: AlertProvider
metadata:
  name: on-call
  namespace: istio-system
spec:
  type: discord
  channel: general
  username: pleeo
  # secret containing the webhook address (optional)
  secretRef:
    name: discord-url
    namespace: istio-system
