apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: ghcr.io/phuongleeo/gitops-demo/frontend
  interval: 1m0s
  secretRef:
    name: ghcr

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: frontend
  namespace: flux-system
spec:
  filterTags:
    pattern: '^main-[a-fA-F0-9]+-(?P<bid>.*)'
    extract: '$bid'
  policy:
    numerical:
      order: asc
