apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - istio-manifests.yaml
  - kubernetes-manifests.yaml
namespace: default
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
        - name: ghcr
