name: Build and Push Images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    #   pull-requests: write
    #   actions: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Install dependencies
        timeout-minutes: 10
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          chmod +x skaffold && \
          sudo mv skaffold /usr/local/bin
          echo "✅ skaffold installed"
      - name: read secrets
        run: |
          echo "${PACKAGES_TOKEN}" > packages-token.txt
          cat packages-token.txt
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        # timeout-minutes: 20
        # run: |
        #   skaffold build --default-repo ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --tag=${GITHUB_SHA:0:7} --file-output=tags.json
        uses: hiberbee/github-action-skaffold@1.10.0
        with:
          skaffold-version: 1.33.0
          command: build
          repository: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tag: ${{ github.sha }}
      # - name: "Upload Artifact"
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: skaffold-tags
      #     path: tags.json
